CREATE TABLE mountain_info 
    (id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255),  
    region VARCHAR(255),  
    number VARCHAR(255),  
    lat FLOAT, 
    lon FLOAT,  
    address VARCHAR(255), 
    image VARCHAR(255), 
    apex FLOAT,
    level VARCHAR(255),
    feature LONGTEXT,
    summary LONGTEXT, 
    point LONGTEXT, 
    best_course VARCHAR(255),
    run_time INT,
    course1 VARCHAR(255),
    run_time1 INT,
    course2 VARCHAR(255),
    run_time2 INT,
    course3 VARCHAR(255),
    run_time3 INT,
    course4 VARCHAR(255),
    run_time4 INT,
    traffic LONGTEXT,
    PRIMARY KEY (id));